### ISSUE TITLE
Shortcut displayed on the help page don't work on Mac

### ISSUE THREAD

**Issue by quark67** [learnlatex/learnlatex.github.io#179]
In the file `en/help.md`, we read (for setting a theme):

```
(<kbd>⌘</kbd>+<kbd>,</kbd> on Mac)
```

(In the following, I write `cmd` instead of `⌘` as the later is perhaps not displayed in all operating system; it's the *command* key)

This don't work on the Safari browser: the shortcut `cmd`+`,` is the standard shortcut of a Mac application for its preferences (settings).

If I press `cmd`+`,` the window of Safari preferences is opened.

**Comment by joulev** [comment]
<kbd>⌘</kbd>+<kbd>,</kbd> is [the default keyboard shortcut for Ace editor](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts#other) which LearnLaTeX uses.

I don't have a Mac, but try clicking inside the editor and then <kbd>⌘</kbd>+<kbd>,</kbd>, probably it will open the editor settings instead of Safari preferences.

Such shortcut clashes also occur in other browsers too, for example I'm using Firefox and <kbd>Ctrl</kbd>+<kbd>L</kbd> mean both "go to line" in Ace and "go to URL bar" in Firefox. Which action to be done depends on whether the Ace editor is "active" or not (in other words if I click on the editor then <kbd>Ctrl</kbd>+<kbd>L</kbd> it will be "go to Ace line", but normally it will "go to URL bar").

**Comment by josephwright** [comment]
This looks Safari-specific - the override works in Firefox and Chrome

**Comment by davidcarlisle** [comment]
If there is no keybinding that shows that in Safari I could (I think) add a link in the help page that opens the editor with that panel open. You don't really need it while editing the examples on the site but it is useful to experiment with alternative themes similar to this link on the ACE site that opens the editor with the keybindings list (rather than settings menu) open  https://ace.c9.io/demo/keyboard_shortcuts.html

**Comment by davidcarlisle** [comment]
If you look at the English help you should be able to access the ace settings on that page at least by using the link on the word **panel**. If that works I may change the wording a bit to make it more obvious and push it across the translated help pages.

**Comment by quark67** [comment]
Yes, it works by clicking on the word **panel**, thanks (by the way, on the French translate, the shortcut was mistakenly wrote as `?`+ `,`, instead `⌘`+ `,`, this is how I found the bug).

**Comment by jejust** [comment]
Hi @quark67,
Yes, sorry, my setup is not fully UTF8 compliant yet. Thank you for noticing the mistake!
Feel free to report me other problems in the French version.

**Comment by quark67** [comment]
@jejust Here's a pull request: https://github.com/learnlatex/learnlatex.github.io/pull/180

**Comment by jejust** [comment]
Good job!
