### ISSUE TITLE
LaTeX online leads to PDF files downloaded again and again

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#53]
Context
-------
- Linux Mageia 7
- Firefox 77.0.1 (64 bits) with (blindly translated) Options → Applications → Portable Document Format (PDF) →"Download" or "Use the default application" (not "Preview In Firefox")

Issue
-----
When the "LaTeX online" button is clicked, the generated file is downloaded again and again until "Delete the output" is clicked.

Remark
----
If the chosen action for PDFs is "Preview In Firefox", the resulting output is shown "in the page" as expected, but I generally don't like PDFs I download to be displayed in Firefox .

**Comment by davidcarlisle** [comment]
@dbitouze  Yes this is a known issue, I've considered disabling the latex online button but I don't think that you can distinguish this from javascript in the page. Mobile clients (including mobile firefox) is that way by default, you can detect the mobile user agent string but that's not a very robust test and doesn't help detect a desktop browser that's set up to download or use an external viewer.

I have a test server that uses PDF.js so should always open up in-page (this is what Overleaf also uses) but it's not ready for public testing yet.

**Comment by davidcarlisle** [comment]
_Edited highlights from an email conversation, copied here for the record._

----

Currently on learnlatex.org the result is served as:

```
content-type application/pdf
document.pdf
```

so that it does whatever your browser does with PDF. On desktop it shows in-page for most people
but on mobile or if you have configured an external viewer it downloads the pdf and (perhaps)
opens a new viewer leaving an empty iframe in the page (as the page can't tell that happened:(


A different possibility would be to host PDF.js and serve the result as:  

```
content-type text/javascript
PDF.js?file=document.pdf
```

so it does whatever your browser does with javascript, most likely render in-page but if you have disabled javascript it won't work but in the learnlatex.org setting without javascript you would get no buttons added so have no access to this at all.


A third possibility would be to serve the result as

```
content-type application/octet-stream
document.pdf
```

Then the file will never be rendered: it will trigger the browser's "save file" dialogue


---

My idea is that (somewhere on learnlatex.org) there would be a possibility for a user option to choose from these three possibilities.
If the site knew the PDFs were being rendered externally or downloaded it would not open the unused white iframe

This could be per-example by adding one of the following lines:

```
% !TEX PDF.js
% !TEX  PDF.browser
% !TEX PDF.download
```

using the existing magic `!TEX` comment syntax, or (if the user accepts cookies) perhaps we could have a site-default setting for preferred defaults.


 





----
----
> Just a small remark: when the user is at the bottom of the page, so is
> the button and, if the latter is clicked, the resulting
> output is displayed below but stays hidden until the user goes down.
> 

Yes something we could flag with Jonas who is looking at overall site styling, that is purely a feature
of the html side and applies equally to all of the back end latex servers. Should be easy to detect and
scroll when opening the iframe if you are within some specified distance of the bottom of the window.

**Comment by davidcarlisle** [comment]
@dbitouze  could you please try the version linked from  https://latexcgi.xyz/ It uses PDF.js and should address this issue I think.
That page links to a slighly older copy of the learnlatex examples,  but using a new latex server being tested.

**Comment by dbitouze** [comment]
@davidcarlisle I tested the examples at https://latexcgi.xyz/test.html (Firefox 77.0.1 64 bits with Options → Applications → Portable Document Format (PDF) →"Download" or "Use the default application" (not "Preview In Firefox")).

1. "A LuaTeX example, test switching to xetex": empty output (white iframe) and (annoyingly) `.log` file downloaded (and open with the default editor).
1. "An example with no extra files": works nicely.
1. "An error case": same as 1st example.

**Comment by PhelypeOleinik** [comment]
> 1. "A LuaTeX example, test switching to xetex": empty output (white iframe) and (annoyingly) `.log` file downloaded (and open with the default editor).

This one shows the `.log` because it errors:
```none
! LaTeX Error: File `article.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
   
l.3       \begin
              {document}
End of file on the terminal!
```

**Comment by davidcarlisle** [comment]
@dbitouze  @PhelypeOleinik  sorry about that it was working but I flipped the texmf.cnf setting to

`openin_any = p`

which in intended to stop people reading files by absolute path but breaks luatlatex's file search completely

https://tex.stackexchange.com/a/293915/2388

There are ways to get the desired behaviour but not for a few hours, sorry.

**Comment by davidcarlisle** [comment]
latexcgi.xyz is now live on the site, so closing this.
