### ISSUE TITLE
Line numbers in code blocks

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#59]
more-15:

> Here the error will be reported on line 11
> ```
> l.11 \end{align}
> ```
> Although the real error is on line 9 as shown by the context lines:
> ```
> ! Undefined control sequence.
> <argument> ...ha &= \frac {1}{2}\\ \beta &= \frak 
>                                                   {2}{3}\\ \gamma &= \frac {...
> ```

As the lessons sometimes refer to line numbers in the code, maybe we should add line numbers to the code blocks?

**Comment by davidcarlisle** [comment]
Perhaps, but it's not entirely trivial to add. I just added

```
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
```

to the  `_config.yml` at 

https://davidcarlisle.github.io/ll/en/lesson-12

The result isn't good:-)

![image](https://user-images.githubusercontent.com/1268738/87285362-588bb480-c4ef-11ea-8d39-acc62137f019.png)


Adding line numbers there changes the element structure and breaks all the current code, it is no doubt fixable but I've been trying to avoid too much code that is specific to the particular page builder in use.  It may be simpler to add the line numbers "by hand" in javascript/css at the end rather than getting the rouge syntax highlighter to do it before the page code starts.

Either way, I think this has to be postponed as a "possible future enhancement"

**Comment by josephwright** [comment]
One to ask @jonasjacek about: other sites do manage this (https://www.learnpython.org/en/Hello%2C_World%21 for example).

**Comment by davidcarlisle** [comment]
@josephwright  the boolean linenumbers option in the config.yml  works but as in the example you link to it changes the structure from a single pre containing the code to a div with two nested pre one for the numbers and one for the code. That would be fine except here we have the site javascript expecting to find a single element to add the buttons to, and not expecting to have to remove the line numbers before submitting to the latex servers. 

It's probably only a minor change in each place, once you work out how the line numbers are built, it would just be a matter of changing some "child" selections to "get second grandchild" or whatever, but it affects more or less all the current code, as the image above shows, the buttons get added three times, and none of them work as they pick up the line numbers as text so it's a change we can do but need to commit to a particular highighting configuration first, as the button and posting code makes a lot of assumptions about the element structure.

**Comment by davidcarlisle** [comment]
@josephwright  the other issue is if you want the line numbers to re-sync as you edit, if so the rouge highlighter numbering will not really work as that is part of the static page generation. The python example is using the embedded ACE editor (I think that is also what overleaf use) I did do a few tests using that originally although we decided to stick to a simple contenteditable div and defer to overleaf etc for more extensive editing.
