### ISSUE TITLE
CONTRIBUTING.md has broken links to CHANGELOG.md and AUTHORS.md

### ISSUE THREAD

**Issue by rvente** [learnlatex/learnlatex.github.io#79]
I noticed the links to CHANGELOG.md and AUTHORS.md files in [CONTRIBUTING.md](https://github.com/learnlatex/learnlatex.github.io/blob/master/CONTRIBUTING.md) were not working. For example, the changelog link goes to `https://github.com/learnlatex/learnlatex.github.io/blob/master/CHANGELOG`, which resolves to a page not found.

It appears this was deliberate, evidenced by  learnlatex/learnlatex.github.io@cae48e6 but I wanted to point it out in case there have been changes since then. If I've overlooked something, please let me know.

**Comment by davidcarlisle** [comment]
These are source files, the local links to the generated .html files and their extension free aliases do not work in that location but the generated files are fine:  the generated file is at the github pages site 

https://www.learnlatex.org/CONTRIBUTING

(now the site URL is fixed, we could use absolute URL to learnlatex.org in all cases so the links work anywhere which I just did for the similar  issue #68 )

**Comment by rvente** [comment]
Ah, I see. I could take this one and open a PR. Same changes as those in 8ee38f2 correct?

**Comment by davidcarlisle** [comment]
well perhaps but to be honest I'm not sure. There are a few of these top level files where people seem to land on the git source and are confused by the incomplete preview of the markdown shown by github. We could change them to use absolute links but the issue is throughout the site eg links from one lesson to another also do not work if you are in the markdown sources rather than the generated site. I would not agree with making those all absolute to the  learnlatex URL, apart from anything else any of these absolute links means that they don't really work on forks as they come back to the main site.

**Comment by davidcarlisle** [comment]
@rvente  actually github pages does support having local links that work between `.md` files in the source view and between the generated HTML on the gh-pages site.

It was announced here

https://github.blog/2016-12-05-relative-links-for-github-pages/

and the relevant jekyll plugin is active by default these days.

However it generates links to URL ending in `.html` and we are consistently using extension-less URL here so lesson-01 not lesson-01.html. The .html ones work but it would be better if the canonical URL were used (or failing that make them redirect)

I'll leave this open, and experiment to see if it can be configured not to add .html.
If we could do that, that would be a better fix than the fix I used in the other issue of using absolute URL.

**Comment by davidcarlisle** [comment]
@rvente  I think that fixed it, the trick is adding a `permalink:` metadata (which I should probably push out over all of the files)

**Comment by rvente** [comment]
The fix works great! Very nice.
