### ISSUE TITLE
Remove languages that are not yet translated from _config.yml

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#92]
Japanese and Chinese are currently live but the `master` version has no translation for these languages yet. So I reckon they should be removed from the site temporarily until when the translation process is done, shouldn't they?

The German translation is incomplete too, so I suppose it should not be live yet.

To my knowledge many are actively working on the translations for these languages, so I believe if these language are to be taken down, it is only a matter of time until they are live again.

**Comment by davidcarlisle** [comment]
Yes I was planning on doing that, as you say in the title just drop them from the config.yml array so they would still be on the site, just dropped from the navigation menu.

Conversely (since the translations for Marathi, Japanese and Chinese do have several pages in their respective forks) I wonder if @jonasjacek would find it useful if PRs were made from  the forks to the design branch to see the test site with non latin scripts?

eg

https://github.com/CTeX-org/learnlatex.github.io/blob/zh-hans/zh-Hans/lesson-02.md

https://github.com/wtsnjp/learnlatex.github.io/blob/translation-ja/ja/lesson-03.md

https://github.com/NiranjanTambe/learnlatex.github.io/blob/master/mr/lesson-03.md

**Comment by jonasjacek** [comment]
For now, I focus on latin scripts, mainly english. Adaptions for other scripts will follow afterwards.
